/*
 * splash_anim.cpp - animated POSEIDON boot splash for the T-Embed's 320x170 panel.
 *
 * Plays the type-motion wordmark reveal generated by
 * scripts/convert_splash_anim.py into src/sprites/splash_anim.h.
 *
 * WHY STREAMING, NOT A FRAMEBUFFER:
 *   A 320x170 RGB565 frame is 108 KB. Allocating that (even in PSRAM) during
 *   boot competes with the radio stacks for heap, and the whole point of the
 *   splash is that it runs before anything else is up. Instead the RLE stream
 *   is decoded straight into ONE row buffer (640 bytes, static) and each
 *   completed row is pushed to the panel. Constant RAM, no allocation, no
 *   PSRAM dependency.
 *
 * Runs cross row boundaries in the encoded stream (that is what makes the
 * black background compress), so the inner loop splits a run at the row edge.
 *
 * Board-gated: the frame data is authored at 320x170, so this is T-Embed only.
 * The Cardputer keeps the classic wave splash in splash.cpp.
 */
#include "app.h"

#if defined(POSEIDON_BOARD_TEMBED)

#include "splash_anim.h"
#include "input.h"
#include "board/leds_tembed.h"
#include "sprites/splash_anim.h"

/* One decoded scanline. Static, not stack: 640 bytes would be a rude thing to
 * put on the boot task's stack, and this function is called exactly once. */
static uint16_t s_row[SPLASH_ANIM_W];

/* Decode one RLE frame and blit it row by row at (x0, y0). */
static void draw_frame(const splash_frame_t &f, int x0, int y0)
{
    auto &d = M5Cardputer.Display;
    const uint32_t total = (uint32_t)SPLASH_ANIM_W * (uint32_t)SPLASH_ANIM_H;
    uint32_t px = 0;   /* pixel cursor within the frame, row-major */

    for (uint32_t i = 0; i + 1 < f.rle_len && px < total; i += 2) {
        /* Palette index is a raw byte from the header; clamp it rather than
         * trusting it, so a truncated/corrupt table can't read past the
         * palette array (which is only SPLASH_ANIM_COLORS entries). */
        uint8_t  idx = f.rle[i];
        if (idx >= SPLASH_ANIM_COLORS) idx = 0;
        const uint16_t c = f.pal[idx];

        uint32_t run = f.rle[i + 1];
        if (run == 0) continue;                    /* defensive: empty run */
        if (px + run > total) run = total - px;    /* defensive: overlong run */

        while (run) {
            const uint32_t col = px % SPLASH_ANIM_W;
            uint32_t n = SPLASH_ANIM_W - col;      /* room left in this row */
            if (n > run) n = run;

            for (uint32_t k = 0; k < n; ++k) s_row[col + k] = c;
            px  += n;
            run -= n;

            if ((px % SPLASH_ANIM_W) == 0) {       /* row filled -> push it */
                const int y = (int)(px / SPLASH_ANIM_W) - 1;
                /* rgb565_t cast: the bare uint16_t* overload is the TFT_eSPI
                 * one and reads the data as byte-swapped 565, which mangles
                 * the palette colours. Name the type so the conversion is
                 * explicit. (Same trap as picons.cpp.) */
                d.pushImage(x0, y0 + y, SPLASH_ANIM_W, 1,
                            reinterpret_cast<const lgfx::rgb565_t *>(s_row));
            }
        }
    }
}

void splash_anim_play(uint32_t frame_ms)
{
    auto &d = M5Cardputer.Display;

    /* Centre the artwork if the panel is larger than the authored frame. */
    const int x0 = (SCR_W - SPLASH_ANIM_W) / 2;
    const int y0 = (SCR_H - SPLASH_ANIM_H) / 2;

    d.fillScreen(0);

    for (int n = 0; n < SPLASH_ANIM_FRAMES; ++n) {
        const uint32_t t0 = millis();
        draw_frame(SPLASH_ANIM[n], x0 > 0 ? x0 : 0, y0 > 0 ? y0 : 0);

        /* Any input skips the rest of the splash - never trap the user in it. */
        if (input_poll() != PK_NONE) return;

        /* Hold the remainder of this frame's slot. Decode time is already
         * spent, so pace against it instead of sleeping a fixed amount. */
        const uint32_t spent = millis() - t0;
        if (spent < frame_ms) {
            const uint32_t left = frame_ms - spent;
            for (uint32_t w = 0; w < left; w += 10) {
                if (input_poll() != PK_NONE) return;
                delay(10);
            }
        }
    }

    /* Rest on the finished wordmark so the splash reads as a title screen
     * rather than flashing past, but NEVER trap the operator here.
     *
     * An unbounded "wait for input" is a boot-time deadlock waiting to happen:
     * if the artwork fails to render, or the input path is wrong on a board,
     * the device sits forever on a blank screen while the loop happily ticks --
     * indistinguishable from a dead device, and unrecoverable without a
     * reflash. Bounded hold means the menu ALWAYS comes up on its own, and a
     * press still skips instantly. */
    const uint32_t HOLD_MS = 30000;   /* long enough to read as "waits for you" */
    const uint32_t t_hold = millis();
    while ((millis() - t_hold) < HOLD_MS) {
        if (input_poll() != PK_NONE) return;
        leds_tick();
        delay(20);
    }
}

#endif /* POSEIDON_BOARD_TEMBED */
